# Frappe ERPNext on Coolify - Fixed compose
version: '3.8'

x-customizable-image: &customizable_image
  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION:-v15}}
  pull_policy: ${PULL_POLICY:-always}
  restart: unless-stopped

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: *depends_on_configurator
  <<: *customizable_image
  volumes:
    - sites:/home/frappe/frappe-bench/sites
  environment:
    DB_HOST: db
    DB_PORT: "3306"
    REDIS_CACHE: redis://redis-cache:6379
    REDIS_QUEUE: redis://redis-queue:6379
    REDIS_SOCKETIO: redis://redis-queue:6379
    SOCKETIO_PORT: "9000"
  healthcheck:
    test: ["CMD-SHELL", "curl -f -s http://localhost:8000 || exit 0"]
    interval: 60s
    timeout: 30s
    retries: 8
    start_period: 180s

services:
  configurator:
    <<: *backend_defaults
    entrypoint: ["bash", "-c"]
    command:
      - |
        set -ex
        echo "=== Configurator started ==="
        cat > /home/frappe/frappe-bench/sites/common_site_config.json << 'COMMON_EOF'
        {
          "db_host": "db",
          "db_port": 3306,
          "redis_cache": "redis://redis-cache:6379",
          "redis_queue": "redis://redis-queue:6379",
          "redis_socketio": "redis://redis-queue:6379",
          "socketio_port": 9000,
          "developer_mode": 1,
          "allow_unsafe_ssl": true,
          "celery": {
            "broker_url": "redis://redis-queue:6379",
            "result_backend": "redis://redis-queue:6379"
          }
        }
        COMMON_EOF
        echo "Common site config:"
        cat /home/frappe/frappe-bench/sites/common_site_config.json
        bench set-config -g db_host db
        bench set-config -gp db_port 3306
        bench set-config -g redis_cache "redis://redis-cache:6379"
        bench set-config -g redis_queue "redis://redis-queue:6379"
        bench set-config -g redis_socketio "redis://redis-queue:6379"
        bench set-config -gp socketio_port 9000
        if [ -d "sites/${SITE_NAME}" ]; then
          echo "Updating existing site config for ${SITE_NAME}..."
          bench --site "${SITE_NAME}" set-config db_host db
          bench --site "${SITE_NAME}" set-config db_port 3306
          bench --site "${SITE_NAME}" set-config redis_cache "redis://redis-cache:6379"
          bench --site "${SITE_NAME}" set-config redis_queue "redis://redis-queue:6379"
          bench --site "${SITE_NAME}" set-config redis_socketio "redis://redis-queue:6379"
        fi
        echo "=== Configurator completed ==="
    environment:
      SITE_NAME: ${SITE_NAME}
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    restart: "no"

  create-site:
    <<: *backend_defaults
    entrypoint: ["bash", "-c"]
    command:
      - |
        set -ex
        echo "=== Create-site started ==="
        sleep 10
        echo "Checking common_site_config.json:"
        cat /home/frappe/frappe-bench/sites/common_site_config.json || true
        if [ -d "sites/${SITE_NAME}" ]; then
          echo "Site ${SITE_NAME} already exists. Updating config and running migration..."
          bench --site ${SITE_NAME} set-config db_host db
          bench --site ${SITE_NAME} set-config db_port 3306
          bench --site ${SITE_NAME} set-config redis_cache "redis://redis-cache:6379"
          bench --site ${SITE_NAME} set-config redis_queue "redis://redis-queue:6379"
          bench --site ${SITE_NAME} set-config redis_socketio "redis://redis-queue:6379"
          mysql -h db -u root -p"${DB_PASSWORD}" -e "SELECT 1" || { echo "DB connection failed"; exit 1; }
          bench --site ${SITE_NAME} migrate || echo "Migration warning"
          echo "=== Site exists, done ==="
          exit 0
        fi
        echo "Creating new site ${SITE_NAME}..."
        ls -la apps/ || true
        mysql -h db -u root -p"${DB_PASSWORD}" -e "SELECT 1" || { echo "DB connection failed"; exit 1; }
        bench new-site ${SITE_NAME} \
          --db-host db \
          --db-port 3306 \
          --mariadb-root-password "${DB_PASSWORD}" \
          --admin-password "${ADMIN_PASSWORD}" \
          --install-app erpnext \
          --force \
          --verbose 2>&1 | tee /tmp/site-creation.log
        if [ $? -ne 0 ]; then
          echo "Last 50 lines of log:"
          tail -50 /tmp/site-creation.log
          exit 1
        fi
        ls -la sites/${SITE_NAME}/ || { echo "Site dir not found"; exit 1; }
        bench --site ${SITE_NAME} set-config developer_mode 1
        bench --site ${SITE_NAME} set-config host_name "https://${SITE_NAME}"
        bench --site ${SITE_NAME} set-config redis_cache "redis://redis-cache:6379"
        bench --site ${SITE_NAME} set-config redis_queue "redis://redis-queue:6379"
        bench --site ${SITE_NAME} set-config redis_socketio "redis://redis-queue:6379"
        bench --site ${SITE_NAME} enable-scheduler
        bench --site ${SITE_NAME} clear-cache
        bench --site ${SITE_NAME} list-apps
        echo "=== Site creation completed ==="
    environment:
      SITE_NAME: ${SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_PWD: ${DB_PASSWORD}
    depends_on:
      configurator:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    restart: "no"

  backend:
    <<: *backend_defaults
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  frontend:
    <<: *customizable_image
    entrypoint: ["bash", "-c"]
    command:
      - |
        echo "Waiting for websocket:9000..."
        until (echo >/dev/tcp/websocket/9000) 2>/dev/null; do sleep 2; done
        echo "Websocket up, starting nginx..."
        exec nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-300}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      backend:
        condition: service_healthy
      websocket:
        condition: service_started
      create-site:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 8
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${SITE_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  websocket:
    <<: *depends_on_configurator
    <<: *customizable_image
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    environment:
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-queue:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  queue-short:
    <<: *backend_defaults
    command: ["bench", "worker", "--queue", "short,default"]
    environment:
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-queue:6379
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully
      redis-queue:
        condition: service_healthy

  queue-long:
    <<: *backend_defaults
    command: ["bench", "worker", "--queue", "long"]
    environment:
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-queue:6379
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully
      redis-queue:
        condition: service_healthy

  scheduler:
    <<: *backend_defaults
    command: ["bench", "schedule"]
    environment:
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-queue:6379
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully
      redis-queue:
        condition: service_healthy

  db:
    image: mariadb:10.11
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-allowed-packet=256M
      - --wait-timeout=28800
      - --max-connections=1000
      - --bind-address=0.0.0.0
      - --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: frappe
      MYSQL_USER: frappe
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DISABLE_UPGRADE_BACKUP: "1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  sites:
  db-data:
  redis-queue-data:

networks:
  default:
    driver: bridge
