version: '3.8'

x-customizable-image: &customizable_image
  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION:-v15}}
  pull_policy: ${PULL_POLICY:-always}
  restart: unless-stopped

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: *depends_on_configurator
  <<: *customizable_image
  volumes:
    - sites:/home/frappe/frappe-bench/sites
  healthcheck:
    test: ["CMD-SHELL", "curl -f -s http://localhost:8000 || exit 0"]
    interval: 60s
    timeout: 30s
    retries: 8
    start_period: 180s

services:
  configurator:
    <<: *backend_defaults
    entrypoint:
      - bash
      - -c
    command: |
      set -ex
      echo "=== Configurator started ==="
      echo "Creating apps.txt..."
      ls -1 apps > sites/apps.txt || echo "Failed to list apps"
      echo "Setting database configuration..."
      bench set-config -g db_host db || echo "Failed to set db_host"
      bench set-config -gp db_port 3306 || echo "Failed to set db_port"
      echo "Setting redis configuration..."
      bench set-config -g redis_cache "redis://redis-cache:6379" || echo "Failed to set redis_cache"
      bench set-config -g redis_queue "redis://redis-queue:6379" || echo "Failed to set redis_queue"
      bench set-config -g redis_socketio "redis://redis-queue:6379" || echo "Failed to set redis_socketio"
      bench set-config -gp socketio_port 9000 || echo "Failed to set socketio_port"
      echo "=== Configurator completed successfully ==="
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    restart: "no"

  create-site:
    <<: *backend_defaults
    command:
      - bash
      - -c
      - |
        set -ex
        echo "=== Create-site started ==="
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la /home/frappe/
        echo "Listing frappe-bench directory:"
        ls -la /home/frappe/frappe-bench/ || echo "frappe-bench directory not found"
        echo "Listing sites directory:"
        ls -la sites || echo "sites directory not found or empty"
        
        # Wait for configurator to fully complete
        echo "Waiting 10 seconds for configurator to settle..."
        sleep 10
        
        # Check if site already exists
        if [ -d "sites/${SITE_NAME}" ]; then
          echo "Site ${SITE_NAME} already exists. Skipping creation."
          bench --site ${SITE_NAME} list-apps || echo "Could not list apps"
          bench --site ${SITE_NAME} migrate || echo "Migration failed"
          echo "=== Site already exists, exiting ==="
          exit 0
        fi
        
        echo "Creating new site ${SITE_NAME}..."
        
        # Check available apps
        echo "Available apps in bench:"
        ls -la apps/ || echo "apps directory not found"
        
        # Test database connection
        echo "Testing database connection..."
        mysql -h db -u root -p${DB_PASSWORD} -e "SELECT 1" || echo "Database connection failed"
        
        # Create the site with maximum verbosity and capture all output
        echo "Running bench new-site command..."
        bench new-site ${SITE_NAME} \
          --mariadb-root-password "${DB_PASSWORD}" \
          --admin-password "${ADMIN_PASSWORD}" \
          --install-app erpnext \
          --force \
          --verbose 2>&1 | tee /tmp/site-creation.log
        
        # Check if site creation was successful
        if [ $? -ne 0 ]; then
          echo "ERROR: bench new-site failed with exit code $?"
          echo "Last 50 lines of site creation log:"
          tail -50 /tmp/site-creation.log
          echo "=== Create-site failed ==="
          exit 1
        fi
        
        # Configure the site
        echo "Configuring site..."
        bench --site ${SITE_NAME} set-config developer_mode 1 || echo "Failed to set developer_mode"
        bench --site ${SITE_NAME} set-config host_name "https://${SITE_NAME}" || echo "Failed to set host_name"
        bench --site ${SITE_NAME} enable-scheduler || echo "Failed to enable scheduler"
        bench --site ${SITE_NAME} clear-cache || echo "Failed to clear cache"
        
        # Verify installation
        echo "Installed apps on site:"
        bench --site ${SITE_NAME} list-apps || echo "Failed to list apps"
        
        echo "=== Site creation completed successfully ==="
    environment:
      SITE_NAME: crm.floriaweb.com
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      DB_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PWD: '${DB_PASSWORD}'  # For mysql client
    depends_on:
      configurator:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    restart: "no"

  backend:
    <<: *backend_defaults
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  frontend:
    <<: *customizable_image
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-300}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      backend:
        condition: service_healthy
      websocket:
        condition: service_started
      create-site:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 8
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${SITE_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  websocket:
    <<: *depends_on_configurator
    <<: *customizable_image
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  queue-short:
    <<: *backend_defaults
    command: bench worker --queue short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  queue-long:
    <<: *backend_defaults
    command: bench worker --queue long
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  scheduler:
    <<: *backend_defaults
    command: bench schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  db:
    image: mariadb:10.11
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-allowed-packet=64M
      - --wait-timeout=28800
      - --max-connections=500
      - --log-bin=mysql-bin  # Enable binary logging for replication
      - --binlog-format=ROW   # Use row-based replication
      - --server-id=1         # Server ID for replication
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sites:
  db-data:
  redis-queue-data:
