version: '3.8'

x-customizable-image: &customizable_image
  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION:-v15}}
  pull_policy: ${PULL_POLICY:-always}
  restart: unless-stopped

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: *depends_on_configurator
  <<: *customizable_image
  volumes:
    - sites:/home/frappe/frappe-bench/sites
  healthcheck:
    test: ["CMD-SHELL", "curl -f -s http://localhost:8000 || exit 0"]
    interval: 60s
    timeout: 30s
    retries: 8
    start_period: 180s

services:
  configurator:
    <<: *backend_defaults
    entrypoint:
      - bash
      - -c
    command: |
      set -ex
      echo "Creating apps.txt..."
      ls -1 apps > sites/apps.txt
      echo "Setting database configuration..."
      bench set-config -g db_host db
      bench set-config -gp db_port 3306
      echo "Setting redis configuration..."
      bench set-config -g redis_cache "redis://redis-cache:6379"
      bench set-config -g redis_queue "redis://redis-queue:6379"
      bench set-config -g redis_socketio "redis://redis-queue:6379"
      bench set-config -gp socketio_port 9000
      echo "Configurator completed successfully"
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    restart: on-failure

  create-site:
    <<: *backend_defaults
    command:
      - bash
      - -c
      - |
        set -ex
        echo "Current directory: $(pwd)"
        echo "Checking sites directory..."
        ls -la sites || echo "sites dir missing"
        
        # Wait a bit for configurator to fully complete
        sleep 5
        
        if [ ! -d "sites/${SITE_NAME}" ]; then
          echo "Creating new site ${SITE_NAME}..."
          
          # Check available apps
          echo "Available apps:"
          ls -1 apps || echo "No apps directory found"
          
          # Create the site with proper error handling
          bench new-site ${SITE_NAME} \
            --mariadb-root-password "${DB_PASSWORD}" \
            --admin-password "${ADMIN_PASSWORD}" \
            --install-app erpnext \
            --force \
            --verbose 2>&1 || { echo "bench new-site failed with exit code $?"; exit 1; }
          
          # Configure the site
          echo "Configuring site..."
          bench --site ${SITE_NAME} set-config developer_mode 1
          bench --site ${SITE_NAME} set-config host_name "https://${SITE_NAME}"
          bench --site ${SITE_NAME} enable-scheduler
          bench --site ${SITE_NAME} clear-cache
          
          # Verify installation
          echo "Installed apps on site:"
          bench --site ${SITE_NAME} list-apps
          
          echo "Site creation completed successfully."
        else
          echo "Site ${SITE_NAME} already exists. Skipping creation."
          # Run migrations if site exists
          bench --site ${SITE_NAME} migrate || true
        fi
        
        # Final check
        bench --site ${SITE_NAME} list-apps || echo "Warning: Could not list apps"
        echo "Create-site process completed"
    environment:
      SITE_NAME: crm.floriaweb.com
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      configurator:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    restart: "no"

  backend:
    <<: *backend_defaults
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  frontend:
    <<: *customizable_image
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-300}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      backend:
        condition: service_healthy
      websocket:
        condition: service_started
      create-site:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 8
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${SITE_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  websocket:
    <<: *depends_on_configurator
    <<: *customizable_image
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  queue-short:
    <<: *backend_defaults
    command: bench worker --queue short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  queue-long:
    <<: *backend_defaults
    command: bench worker --queue long
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  scheduler:
    <<: *backend_defaults
    command: bench schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
      create-site:
        condition: service_completed_successfully

  db:
    image: mariadb:10.11  # Using 10.11 instead of 11.2 for better compatibility
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-allowed-packet=64M
      - --wait-timeout=28800
      - --max-connections=500
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sites:
  db-data:
  redis-queue-data:
